### ISSUE TITLE
faulty active element in affix

### ISSUE THREAD

**Issue by digitalstaub** [mkdocs/mkdocs-bootswatch#16]
Hello,
for me (chromium 48 and ff 44 on Ubuntu) the affix shows a wrong active element.
This can be seen on
http://mkdocs.github.io/mkdocs-bootswatch/#installation-usage
to.

**Comment by juzraai** [comment]
I also experienced this issue.

It seems the bug is in the scrollspy function of Bootstrap 3.0.3. I replaced the Bootstrap JS file in my template directory to the recent version (3.3.6) and it solved the problem for me. :)

**Comment by digitalstaub** [comment]
I think, in base.js 
`
$('body').scrollspy({
    target: '.bs-sidebar'
});
`
should be:
`
$('body').scrollspy({
    target: '.bs-sidebar',
    offset: 81
});
`

**Comment by d0ugal** [comment]
This is most likely related to this bug: https://github.com/mkdocs/mkdocs/issues/406

**Comment by jimporter** [comment]
Since these themes are derived from the main `mkdocs` theme (which has fixed this issue), this should be ok now.
