### ISSUE TITLE
Load jquery at the top of themes

### ISSUE THREAD

**Issue by bwmarrin** [mkdocs/mkdocs-bootswatch#19]
Hi! I'd like to propose these themes switch to loading jquery at the top of the page (or before user content is added) instead of at the bottom. This matches the behavior of the readthedocs theme.

This change would allow users to use jquery within their documents to spice things up, like many of the examples shown here http://bwmarrin.github.io/MkDocsPlus/

Please also see, bwmarrin/MkDocsPlus#2, https://github.com/mkdocs/mkdocs/issues/956

**Comment by jimporter** [comment]
It appears this was resolved by #23.
