### ISSUE TITLE
Update to "new style" themes and automate generation

### ISSUE THREAD

**Issue by memeplex** [mkdocs/mkdocs-bootswatch#21]
I would like to do this in my scarce free time. Are you using some kind of template to generate the entire family? If not, why?

**Comment by memeplex** [comment]
I noticed there is an open PR that doesn't pass the CI build. I may start looking there. Nevertheless I really would like to automate the entire set generation (if you like the idea) and maybe tackle #7 at the same time.

**Comment by d0ugal** [comment]
No, they are not generated. Yes, they should be.

**Comment by memeplex** [comment]
I'm working on this for the next hours. A diff of the themes shows that two files differ between themes:  bootstrap-custom.min.css and base.css.

Regarding bootstrap-custom.min.css: is it just the css download from the bootswatch site or is it somewhat customized? (I'm asking this because of its filename).

Regarding base.css: what is the criteria to generate it? Just some colors differ:

```
diff amelia/css/base.css journal/css/base.css
65,67c65,67
<     background: #0d747c;
<     border: solid 1px #0a565c;
<     color: #fff;
---
>     background: #f5f5f5;
>     border: solid 1px #ccc;
>     color: #333;
76c76
<     color: #e8d069;
---
>     color: #eb6864;
80c80
<     color: #debb27;
---
>     color: #e22620;
```

are these colors related to the bootswatch theme? How?

**Comment by memeplex** [comment]
Another question: I see the templates are essentially identical to the ones in mkdocs theme, except for the outdated parts. Given that I'm going to automate the generation of the bootswatch suite, do you think it may be better to just checkout the up-to-date mkdocs templates during generation instead of keeping a separate copy that gets outdated too easily?

**Comment by memeplex** [comment]
To summarize the above questions: ideally I would like to get as close as possible to a very streamlined solution similar to:

```
#!/bin/bash

set -e

mkdocs_repo=https://github.com/mkdocs/mkdocs.git
mkdocs_dir=$(mktemp -d)
themes_dir=mkdocs_bootswatch
bootswatch_themes=(cerulean cosmo cyborg darkly flatly journal lumen paper \
                   readable sandstone simplex slate spacelab superhero united \
                   yeti)

git clone --depth 1 --branch master --single-branch "$mkdocs_repo" "$mkdocs_dir"
rm -rf "$themes_dir"
mkdir "$themes_dir"
cd "$themes_dir"
touch __init__.py
for theme in "${bootswatch_themes[@]}"; do
    mkdir "$theme"
    cp -r "$mkdocs_dir"/mkdocs/themes/mkdocs/* "$theme"
    wget -P "$theme/css" https://bootswatch.com/spacelab/bootstrap.min.css
done
```

Now there are some tweaks here and there that I might apply as per-theme diffs on top of the generated tree. Possible candidates are:

1. base.css
2. The custom part in: bootstrap-custom.min.css
3. Divergences between mkdocs theme and bootswatch themes.

Nevertheless, the approach here is tempting because it makes it too simple to keep things up-to-date and eliminates all duplication (which was about 99.9%).

**Comment by memeplex** [comment]
One very simple way to apply small diffs to the different themes is to create a branch T for the theme T, that just tweaks mkdocs_bootwatch/T a bit. Then while generating themes with the script above it's just a matter of merging branch T for each T:

```bash
for theme in "${bootswatch_themes[@]}"; do
    mkdir "$theme"
    cp -r "$mkdocs_dir"/mkdocs/themes/mkdocs/* "$theme"
    wget -P "$theme/css" https://bootswatch.com/spacelab/bootstrap.min.css
    git merge "$theme" # This line is the only required change.
done
```

Each branch will modify base.css and other files.

A second approach is to make these files jinja templates but it's a bit more involved because it's necessary to define the set of theme-specific files upfront and because it's simpler to call git from a trivial shell script like that above than to call jinja.

Please let me know what do you think so I can move forward.

**Comment by memeplex** [comment]
Well, I think I have figured out a solution that:

1. Keeps what was working just as it was.
2. Almost automatically keeps the main theme and the bootswatch themes in sync.
3. Autogenerates all the bootswatch family.
4. Incorporates the new bootswatch themes.
5. It's very simple.

It works as follows:

1. You run the script [gen.sh](https://github.com/memeplex/mkdocs-bootswatch/blob/1e30787604592f02530299a45012aa273220b65a/gen.sh).
2. gen.sh clones and uses the latest mkdocs theme as a base to generate every bootswatch theme.
3. gen.sh downloads every bootswatch theme available (even the deprecated amelia) and replaces bootstrap-custom.min.css.
4. gen.sh applies the diff `gen-base..gen-tweaks` to the resulting themes.
5. At this point you might want to stage the changes, commit and push a new version.

Now, what are gen-base and gen-tweaks?

* **gen-base**: this is a tag pointing to some commit in master that contains the base themes. I don't expect it to change very often.
* **gen-tweaks**: this is a branch based at gen-base (you should rebase it if gen-base changes) containing every tweak to the base themes. Currently it just transforms the mkdocs base.css file into each of the "legacy" bootswatch base.css files (for new themes, the base.css for the most similar theme was used), but it's expected to contain every "tweak" to gen-base. This is explained in this [commit comment](https://github.com/memeplex/mkdocs-bootswatch/commit/7c28fc662262cdb79dadbabf0e0b582ee71a9336).

Given there are some refs involved I'm not able to submit this as a plain PR, but here is a fork with all the changes: https://github.com/memeplex/mkdocs-bootswatch. Hope you like it!

**Comment by memeplex** [comment]
@d0ugal, I have read your comment in https://github.com/mkdocs/mkdocs-bootswatch/issues/17:

> The bootswatch themes are currently lacking a maintainer

I was assuming you were the maintainer. If you like my changes here I could maintain the themes, meaning: I can keep them up-to-date with mkdocs and bootswatch, I can merge PRs and try to fix issues, but not really make the themes look nicer or cool.

**Comment by memeplex** [comment]
I've updated all base.css files to include every new feature in upstream mkdocs theme I considered not to conflict with the bootswatch themes, that is honouring the original colours. For admonitions I just copy pasted the css from mkdocs base.css, I expect colours to be updated incrementally by users interested in one or another theme.

I decided to remove support for the deprecated amelia, since it wreaks havoc with the latest mkdocs theme.

See the updated `gen-base..gen-tweaks` [diff](https://github.com/memeplex/mkdocs-bootswatch/commit/78190ea7d4a23c07d8e478c322c1754eea9b7768).

**Comment by memeplex** [comment]
I've updated my repo after the [recent changes to the mkdocs template](https://github.com/mkdocs/mkdocs/commit/8b6c13f0e07a85502a2d028ddeef3b456fb0285b).

**Comment by memeplex** [comment]
Just to let you know I have updated [my automated bootswatch themes](https://github.com/memeplex/mkdocs-bootswatch) to latest bootswatch 3 and latest mkdocs theme.

**Comment by waylan** [comment]
I haven't actually tried it yet, but autogenerating the bootswatch themes may become completely unnecessary if mkdocs/mkdocs#1201 lands. That PR adds the option for a theme to inherit from another theme. Therefore we could have one master bootswatch theme with the common parts, and each child theme would then provide its own CSS, etc. The parent theme could even be the "mkdocs" theme completely eliminating the need to auto-generate anything.

@memeplex  if you have any feedback on that PR, it would be appreciated.

**Comment by waylan** [comment]
This is no longer necessary due to #48.
