### ISSUE TITLE
Theme Cuts-off top of page

### ISSUE THREAD

**Issue by Jacobbrent15** [mkdocs/mkdocs-bootswatch#26]
Installed the bootswatch package theme, but it cuts off the title pages. 
![image](https://user-images.githubusercontent.com/29800577/27741991-0252cfb0-5d85-11e7-8577-63125452e6e6.png)
(Numbers covered for security reasons)
Any ideas how to fix?

**Comment by jimporter** [comment]
@Jacobbrent15 Does this also happen with the built-in `mkdocs` theme? If it's fixed there, we could probably just port over the relevant changes; if not, we should fix that theme as well.

**Comment by dhbrand** [comment]
![image](https://user-images.githubusercontent.com/25614393/39306726-ec8167e6-492e-11e8-9cff-08fbdf42689e.png)
I'm also seeing the same issue.

**Comment by jimporter** [comment]
This should be fixed in 46c3593c9c551678fab426d534b5666d48f93276, which includes a port of mkdocs/mkdocs#1969.
