### ISSUE TITLE
Support include_next_prev in all themes

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs-bootswatch#4]
See: https://github.com/mkdocs/mkdocs/issues/479

**Comment by tomchristie** [comment]
Note that we *could* implement the same contextual display that the builtin `mkdocs` theme uses, even tho we're dropping `include_next_prev` and `include_nav`

Currently single page displays look like so:

![image](https://cloud.githubusercontent.com/assets/647359/8499256/bf64a5fa-2188-11e5-9d09-832405dfa706.png)

Note the redundant items in the navbar.

**Comment by jimporter** [comment]
Based on mkdocs/mkdocs#681, this should probably be closed.
