### ISSUE TITLE
Yeti and Cosmo themes have a blue header

### ISSUE THREAD

**Issue by mstenta** [mkdocs/mkdocs-bootswatch#63]
I installed Mkdocs and Mkdocs Bootswatch on a new Ubuntu 18.04 machine and now when I build my site with the `yeti` theme the color scheme is different. The header bar is blue, when it should be dark grey.

It appears that `css/bootstrap-custom.min.css` is no longer being added to the page, and so the usual style overrides are not happening.

Could this be something I'm doing wrong? Or a bug in the Mkdocs/Bootswatch stack?

**Comment by waylan** [comment]
What version did you install of both MkDocs and the theme? We just updated both MkDocs and the mkdocs-bootswatch themes to 1.1. The themes are now using Bootstrap 4 (previous version used bootstrap 2). I'm not sure if this is a bug, or if Bootrap/bootswatch changed the theme. @jimporter do you have any input here?

@mstenta if you want to use the old theme with the new version of MkDocs, we are working on a classic version of the bootswatch themes which can currently be found at [jimporter/mkdocs-bootswatch-classic][1]. Hopefully we will get those released soon.

[1]: https://github.com/jimporter/mkdocs-bootswatch-classic

**Comment by mstenta** [comment]
Thanks @waylan - if it helps, you can see what I mean on this testing site: https://mstenta.github.io/farmOS.org/ - FWIW that is being generated with this GitHub Action: https://github.com/mstenta/farmOS.org/runs/467982237?check_suite_focus=true

This is happening with version 1.1 of Mkdocs and 1.1 of Mkdocs Bootswatch.

**Comment by waylan** [comment]
> It appears that `css/bootstrap-custom.min.css` is no longer being added to the page.

The [release notes][1] note that `css/bootstrap-custom.min.css` was renamed `css/bootstrap.min.css` and I can see that the file is loading correctly. But I'm not sure if that is the `yeti` version of the file from bootswatch or not.

[1]: https://www.mkdocs.org/about/release-notes/#update-mkdocs-theme-to-bootswatch-413-1563

**Comment by mstenta** [comment]
Here is the live site, which has not been updated, for comparison: https://farmOS.org

**Comment by mstenta** [comment]
Oh I think I see... in Bootswatch 4+, Yeti has three different header styles... and the new default is blue perhaps: https://bootswatch.com/yeti/

In which case, that isn't a bug with `mkdocs-bootswatch`. I'll close this issue.

Question: `theme_inverse: true` doesn't seem to be having any affect. Has this behavior changed in the new version, perhaps?

**Comment by jimporter** [comment]
> Oh I think I see... in Bootswatch 4+, Yeti has three different header styles... and the new default is blue perhaps: https://bootswatch.com/yeti/

Yeah, the Bootswatch folks changed the default colors. It's sort of annoying, since I don't think most people would expect such a significant color change when upgrading Bootswatch, but oh well...

> Question: `theme_inverse: true` doesn't seem to be having any affect. Has this behavior changed in the new version, perhaps?

The new way to define this is `nav_style: dark`; the other options are `primary` (the default) and `light`. This is in the docs, but since 1.1 isn't out yet, the site still shows the old info.

Of course, as @waylan mentioned above, if you want to use the Bootswatch 2 version of the themes, `mkdocs-bootswatch-classic` will address that. I'll try and do my side of moving the repos around for that in the next day or two. :)

**Comment by mstenta** [comment]
Thank you for all the info @jimporter and @waylan - much appreciated! I ended up switching to a different bootswatch and I'm happy. :-)

**Comment by waylan** [comment]
> This is in the docs, but since 1.1 isn't out yet, the site still shows the old info.

1.1 was released a few days ago, but it appears the docs deployment failed. Fixed now.

**Comment by jimporter** [comment]
> 1.1 was released a few days ago, but it appears the docs deployment failed. Fixed now.

Oh, I didn't realize! I guess I'd better get on with moving `mkdocs-bootswatch-classic` over and updating `mike` then...
