### ISSUE TITLE
Add new Bootswatch themes

### ISSUE THREAD

**Issue by mstenta** [mkdocs/mkdocs-bootswatch#7]
Two (relatively) new Bootswatch themes:

http://bootswatch.com/paper/
http://bootswatch.com/sandstone/

http://news.bootswatch.com/post/94634387436/new-themes-paper-and-sandstone

**Comment by jimporter** [comment]
There's also Darkly, Lumen, and Superhero.

**Comment by ctcampbell** [comment]
Any movement on this?

**Comment by d0ugal** [comment]
@ctcampbell Nope, this is waiting for somebody to come along with enough time and motivation.

**Comment by memeplex** [comment]
See [this comment](https://github.com/mkdocs/mkdocs-bootswatch/issues/21#issuecomment-238033825) for a possible solution.
