### ISSUE TITLE
Themes do not support admonitions

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs-bootswatch#8]
More context: https://github.com/mkdocs/mkdocs/issues/811

**Comment by jimporter** [comment]
I have code for this for Yeti, and could port it to the other themes if you like. Here's the code: <https://github.com/jimporter/bfg9000/blob/master/doc/css/extra.css#L38-L93>, and here it is in action: <https://jimporter.github.io/bfg9000/user/reference/>.

**Comment by memeplex** [comment]
@jimporter I've updated the entire suite of themes, the admonitions are there but with the base mkdocs theme colors, I would be great if you fix that colors (at least light vs dark-background variants). See  a description in #21 and specially branch gen-tweaks in https://github.com/memeplex/mkdocs-bootswatch.
